Feature/#5790 fix format of date v1
tokyo-metropolitan-gov/covid19 pull request #5825
Opened 2020-12-20 11:37 UTC by nard-tech

## 👏 解決する issue / Resolved Issues
- #5750（関連：#5790）

## 📝 関連する issue / Related Issues
- #5790

## ⛏ 変更内容 / Details of Changes
- 各グラフの見出しの日付を，年も含めて表示
- 各グラフの注釈の日付を，年も含めて表示
- グラフのX軸 (cf. #5790)，テーブルの表示内容については別途実装する

## 📸 スクリーンショット / Screenshots

2020-12-20 11:41 UTC, nard-tech commented on components/cards/ConsultationAboutFeverNumberCard.vue
> +                  '集団感染発生や曜日による数値のばらつきにより、日々の結果が変動するため、こうしたばらつきを平準化し全体の傾向を見る趣旨から、過去7日間の移動平均値を折れ線グラフで示す（例えば、2020年5月7日の移動平均値は、2020年5月1日から5月7日までの実績値を平均したもの）'
他のグラフに合わせ，「2020年5月7日の移動平均値は〜」とする．

2020-12-20 11:41 UTC, nard-tech commented on components/cards/TokyoRulesApplicationNumberCard.vue
> +                  '集団感染発生や曜日による数値のばらつきにより、日々の結果が変動するため、こうしたばらつきを平準化し全体の傾向を見る趣旨から、過去7日間の移動平均値を折れ線グラフで示す（例えば、2020年5月7日の移動平均値は、2020年5月1日から5月7日までの実績値を平均したもの）'
他のグラフに合わせ，「2020年5月7日の移動平均値は〜」とする．

2020-12-20 11:42 UTC, nard-tech commented on components/cards/TokyoFeverConsultationCenterReportsNumberCard.vue
> +                  '曜日などによる数値のばらつきにより、日々の結果が変動するため、こうしたばらつきを平準化し全体の傾向を見る趣旨から、過去7日間の移動平均値を折れ線グラフで示す（例えば、2020年11月7日の移動平均値は、2020年11月1日から11月7日までの実績値を平均したもの）'
他のグラフに合わせ，「2020年5月7日の移動平均値は〜」としたいところだが，グラフが2020年10月30日からのデータを表示しているので，「2020年11月7日の移動平均値は〜」とする．（「11月16日の移動平均値は〜」より例としてわかりやすいため）

2020-12-20 11:53 UTC, kaizumaki commented
@nard-tech ご対応ありがとうございます。こちらにもコメントしていますが https://github.com/tokyo-metropolitan-gov/covid19/issues/5750#issuecomment-736216245 注釈についてはTransifex上で翻訳がリセットされてしまうため、対応としては後回し（別PR）にしていただけますでしょうか 🙇‍♀️

2020-12-20 11:55 UTC, nard-tech commented
@kaizumaki おっと，すみません．翻訳部分は別にします．

2020-12-23 13:05 UTC, kaizumaki requested changes
こちら東京都のOKが出ましたのでマージしたいのですが、 https://github.com/tokyo-metropolitan-gov/covid19/pull/5828#issuecomment-748769096 の対応をお願いしてもいいでしょうか？
こちらでいうと `getDayjsObject` が不要になると思うのです。

2020-12-23 13:42 UTC, nard-tech commented
@kaizumaki 承知しました．

2020-12-23 22:29 UTC, kaizumaki approved these changes
ありがとうございます！LGTM!

2020-12-24 00:52 UTC, merged