fix ogp
tokyo-metropolitan-gov/covid19 pull request #5855
Opened 2020-12-28 00:40 UTC by mcdmaster

## 👏 解決する issue / Resolved Issues
- close #5421 

## 📝 関連する issue / Related Issues
- #5463 

## ⛏ 変更内容 / Details of Changes

- `Nuxt.js` `metaInfo:` の追加
- 上記による、メタデータの `template:` の有効化 ※これまで有効化されていなかったもの
- (補足) `vue@3` に向けた `Vue.options()` や `Vue.extend()` の非推奨化に伴う、`export default` 方法の変更

## 📸 スクリーンショット / Screenshots

![スクリーンショット 2020-12-28 092234](https://user-images.githubusercontent.com/10361533/103182651-807da180-48f0-11eb-9050-eae77975696d.png)
![スクリーンショット 2020-12-28 092220](https://user-images.githubusercontent.com/10361533/103182660-92f7db00-48f0-11eb-9347-0f85128e0b03.png)

2020-12-28 13:11 UTC, mcdmaster commented
Facebok シェアデバッガの結果はこちらをどうぞ：
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-5855--dev-covid19-tokyo.netlify.app%2Fcards%2Fnumber-of-confirmed-cases%2F

2021-01-05 00:50 UTC, kaizumaki commented
@mcdmaster ご対応ありがとうございます！シェアデバッガを見たところ、ちゃんと更新日時のテキストが反映されていますね！
ところで `og:image` が効いていないのは原因わかりますか？

2021-01-05 04:17 UTC, mcdmaster commented
@kaizumaki イメージだけじゃなく、`description` も効いていないですね。
こりゃたいへん。
`AppLink.vue` に渡す値がまずいんでしょうか。しばしお時間を頂戴したく

2021-01-06 00:44 UTC, mcdmaster commented
最新版をコミットしました。Facebook シェアデバッガの URL はこちら。
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-5855--dev-covid19-tokyo.netlify.app%2Fcards%2Fnumber-of-confirmed-cases%2F

`Nuxt + Vue` の混成環境では、いろいろとおかしな事象が見つかりますね。
- 各項目（`Vue` では `vmid:`、`Nuxt` では `hid:`） ごとに `template:` 属性を使う場合、`Nuxt` 環境下では `vue-meta` のルールに沿って書いた `template:` が機能しない（原因不明：後で Nuxt 側に PR を出しておこうかと）
- `template:` を機能させるためには、`Vue` では値を与える必要がなかった `content:` 属性を指定してやる必要がある
- ただしいったん `template:` の値を与えれば、他の `hid:` の `content:` の値として再利用可能となる（そりゃ template ですもんね）
- `Vue` 環境では、`template:` 属性の式で値が定まれば、`content:` 属性に明示的な値を示す式を書く必要はなかった。`Nuxt` では、それは通用しないルールになっている

以下は、ローカルで取ったスクショです。
![スクリーンショット 2021-01-06 090613](https://user-images.githubusercontent.com/10361533/103715117-245b0180-5003-11eb-83e6-c27e056a63f6.png)

2021-01-06 06:35 UTC, kaizumaki commented
@mcdmaster シェアデバッガ見ました。よさそうですね！
ちなみに「Nuxt + Vue の混成環境」とのことですが、どのあたりが混ざっているのでしょう...？もし混ざっていることがよくない状態だとしたら、Nuxtのルールに寄せる方向でいったほうがいいと思うのですけどね。

2021-01-06 06:39 UTC, kaizumaki commented on pages/cards/_card.vue
>  /* eslint-disable simple-import-sort/sort -- ブラウザでの表示順に合わせて各 card の component を import する */
import文の順番はlintによって入れ替わってしまった感じでしょうか？この `eslint-disable` は効いていなかったりしますかね？

2021-01-06 07:17 UTC, mcdmaster commented on pages/cards/_card.vue
>  /* eslint-disable simple-import-sort/sort -- ブラウザでの表示順に合わせて各 card の component を import する */
@kaizumaki 上のご質問とまとめて回答しますね。
- `Vue + Nuxt `の混ざった部分：これは、混ざった部分と申しますか、`Nuxt` でカイゼンを図った部分がどうにもアダ（アレ？）になっていそうな部分のことに触れた方がよさげです。たとえば、`template:` 句が実際には効いてなかった件は、`metaInfo` の定義の仕方にちょっとした工夫（実項目が `template` を参照するようにする）が必要で、そこは混乱を招いていたように考えられます。`Nuxt` に寄せる方針には、原則賛成です。
- カード `import` が入れ替わった原因は、私はちょっとわかりません。もちろん、意図して入れ替えるといったことはさすがに~~面倒くさいので~~やりません。ご察しのように `yarn lint:fix` は通しています

2021-01-08 03:12 UTC, mcdmaster commented
ソースがだいぶ整理できたので、私の側は、[このコミット](https://github.com/tokyo-metropolitan-gov/covid19/pull/5855/commits/dcc46b0ab0dc782c087bfa2903a1fa4b207148bf)をもち、勝手ながらいったん休止します。
FB デバッガのアウトプットは、こちら（再掲）をご覧ください。
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-5855--dev-covid19-tokyo.netlify.app%2Fcards%2Fnumber-of-confirmed-cases%2F

カード・エントリの `import` の順番は、やはり `eslint` が余計なお世話をして変えてしまいますね。
今のところは、手作業で復旧を目指すのも作業フローとして若干の違和感があったため、`eslint` 通過後のままにしてあります。
その他、インポート可能なツール類はでき得る限り `Nuxt` に寄せています。`Vue-meta` さえももはや登場しません。

この方針が accept されるようでしたら、他の `Vue-meta` 使用分も同じ変更をすることで使用モジュールの削減およびそれに伴うメンテ性の向上を期待できると思っています。オーケーをいただけたら、別途 PR を出します

2021-01-08 03:13 UTC, mcdmaster commented on pages/cards/_card.vue
>  /* eslint-disable simple-import-sort/sort -- ブラウザでの表示順に合わせて各 card の component を import する */
新しいコミットを実施したため、このスレッドはいったんクローズとさせてください

2021-01-08 04:22 UTC, kaizumaki commented
@mcdmaster もろもろありがとうございます！ 🙏  いい感じになっているとは思うのですが、こちらのPRの最初のほうではdescriptionに「YYYY/MM/DD 更新：」と日付が入っていたのですけど、現在のシェアデバッガを見ると消えてしまっています。もともとのissueの内容が「更新日時を入れたい」ということだったので、ちょっと惜しいですね...。

2021-01-08 04:38 UTC, mcdmaster commented
@kaizumaki えっ？ローカルでは日付があるのを確認したのに、そういうこともあるんですか。驚きです。
`pages/cards/_pages.view` しかタッチしていないという意味では、プレビュー版 Netlify も同じモノがのっかっているはずなんですけどね。

`layouts/default.vew` まで遡って見るべしということでしょうか？日付 `updatedAt` は、この `pages/cards/_pages.vue` ではセットしていないため、正直ちょっと困ってしまいました

2021-01-08 15:04 UTC, mcdmaster commented
@kaizumaki ちょっと思うところがあったため、`head()` ディレクティブを使うモジュールの全てに手を入れてみました。
そうすると、ブラウザ拡張機能で見た場合と FB Debugger のときとでは、おそらくプレビュー環境に対するアクセス元制限等の理由で、結果として異なるヘッダ内容が返ってきているものと思われます。

※プレビュー URL（再掲）
https://deploy-preview-5855--dev-covid19-tokyo.netlify.app/

- FB デバッガ実行分（※スクショ省略）
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-5855--dev-covid19-tokyo.netlify.app%2Fcards%2Fnumber-of-confirmed-cases%2F

- ローカルデバッガ（ブラウザ拡張機能）実行分
![スクリーンショット 2021-01-08 235235](https://user-images.githubusercontent.com/10361533/104029740-b20a3d00-520d-11eb-97b0-9a505ef78e98.png)

2021-01-11 12:33 UTC, mcdmaster commented
@kaizumaki 三連休をいいことにいろいろ試してしまいました。
いったん、下のスクショのイメージを勝手ながらチェックポイントとしたく

![スクリーンショット 2021-01-11 211827](https://user-images.githubusercontent.com/10361533/104182962-98a70200-5454-11eb-9332-754b6e57d09e.png)

2021-01-13 01:38 UTC, kaizumaki commented on components/AppLink.vue
> +const options: NuxtConfig = {
すみません、`export default Vue.extend` ではなく `const options: NuxtConfig` を使う書き方って一般的なんでしょうか...？参考にされたものなどあれば教えていただけると幸いです 🙏

2021-01-14 14:46 UTC, mcdmaster commented on components/AppLink.vue
> +const options: NuxtConfig = {
すいません、本業（？）のために出遅れました。

まず、一般的かどうかという問いに対しては、一般的でないという答を返すことになります。
というのも、`Vue.extend()` や `Vue.component()` などのメソッドを使う `vue@2` がいまだ根強く残る現状、それらの方が「一般的」なのは間違いないからです。
世界的に見ても、`NuxtConfig` タイプは未だ一般的でないかもしれません。

ただし #5667 で実験的にやっている `vue@3` 移行トライアルでは、上記２メソッドはいずれも使えません。非推奨ではなく、使えないのです。
だとしたら、`vue@3` 基準と `vue@2` 基準が併存している今のうちにできるところから始めるのは悪くないアプローチだという思惑がありました。
あと、`NuxtConfig` タイプを参照しているのは、あらゆる artifacts を `nuxt` に寄せるという意図を示してます。もしも `vue` だと、`ComponentOptions` タイプを参照（強調？）することになるでしょうか。

参考文献としては、ほかでもない #4923 をご覧ください。そのポリシにのっとって作業をしたつもりです。

あ、グッドデザイン賞受賞おめでとうございます！

2021-01-15 03:55 UTC, mcdmaster commented on components/AppLink.vue
> +const options: NuxtConfig = {
@kaizumaki 補足です。

いずれ `vue@3` が主流となり `vue + nuxt` の構成がより広く使われるようになれば、間違いなく「一般的」にはなります。もしかしたら、このサイトの事例を元に現時点で新たな挑戦を試みる方々も現れるかもしれません。

とはいえ、実績がないコンフィグのリスクをどこまで許容できるか、あるいはあえて選好的・先行的にリスクを取りに行くか、という点については、議論の余地があるのは理解しています。
ですので、採否のご判断はお任せしたいというのが今の私の立場だと思っています。採用・却下のどちらでも、私自身は満足です

2021-01-15 04:05 UTC, kaizumaki commented on components/AppLink.vue
> +const options: NuxtConfig = {
@mcdmaster 解説ありがとうございます！vue@3については、こちらのPRとは別にissueの段階で議論したいですね。

2021-01-15 16:36 UTC, mcdmaster commented on components/AppLink.vue
> +const options: NuxtConfig = {
@kaizumaki あと、`vue@3` がらみと言えるかどうか不確かなのですけど、以下のような改修も行っています。
- `vue-meta` モジュールの排除（じっさいには、`@nuxt/types` を経由して間接的に `vue-meta` が参照されます）
- メタデータの更新方法の精緻化（詳しくは[こちら](https://stackoverflow.com/questions/61330023/how-to-update-vue-meta-on-route-url-change)）

当初のイシューであった `ogp` メタデータの更新不具合の解決の途上、特に上記２点を反映することでより望ましいメンテナンス性をもたらすというタナボタ的効果が発見できました。
`vue-meta` をあえて使わない手段が奏功したとも言えます。

上記に該当するのは、以下のモジュール群となります。できれば、これらは `vue@3` よりも先行してリリースしたいという希望がやはり首をもたげてきました(笑)
- `nuxt.config.ts`
- `package.json`
- `yarn.lock`
- `layouts/default.vuw`
- `pages/cards/_card.vue`

ご検討をいただけますと幸いです

2021-01-18 05:02 UTC, kaizumaki commented on components/AppLink.vue
> +const options: NuxtConfig = {
ああ、なるほど、nuxtにvue-metaが内包されているにもかかわらず、vue-metaがインストールされている状態なのですね。
遡るとこちら #5073 でvue-metaをインストールするに至ったみたいですが、そちらと整合性はとれるでしょうか...？

2021-01-18 08:43 UTC, mcdmaster commented on components/AppLink.vue
> +const options: NuxtConfig = {
@kaizumaki 
整合性という意味では、特に差し障りがあるとは私は感じません。とはいえ、私の判断だけではさすがにリスクはあるでしょうから、 @kaizumaki さんのような識者の方のインプットは欠かせません。

ちなみに、 #5142 で `Renovate` の対象モジュールの整理を検討した際、 `vue-meta` が除外対象としていったん挙げられたことがあります。しかしながら、`import` 句で明示されている以上それは削除できないという結論に至りました。
おっしゃるように、`nuxt` に内包されている、かつプロジェクト方針として `nuxt` に寄せる方針があるのなら、よほど特別な理由がない限りはあえて方針に反して外出しモジュールの `vue-meta` を残し続けるよりも、バンドルされた `vue-meta` コンポーネントを使えばモジュールのバージョンコントロールリスクは `nuxt` に移転できるという、プロジェクトの方針にも寄与するメリットが生まれます。

そうした意味では、TypeScript 系のモジュール（`Prettier` などを想定）もまとめられると睨んでいますけれども、それは別の機会に譲ります

2021-01-19 04:10 UTC, kaizumaki commented on components/AppLink.vue
> +const options: NuxtConfig = {
> ちなみに、 #5142 で Renovate の対象モジュールの整理を検討した際、 vue-meta が除外対象としていったん挙げられたことがあります。しかしながら、import 句で明示されている以上それは削除できないという結論に至りました。

そうですね、過去にそうした議論があって、その意見を採用したので、先祖返りするのはなるべく避けたいところです。
vue-metaに関して言えば、この↓importが解決できればこのPRは先に進めるのかなと思うのですが、vue-metaをアンインストールするまではないのではとも思っています。

https://github.com/tokyo-metropolitan-gov/covid19/blob/9289d5a54f374a4e4c6caa228b417a7b1f3aa313/utils/i18nUtils.ts#L2

どうでしょう、このPRについては最小限の変更にとどめていただいて、ogpのdescriptionに更新日時が反映されるという当初の目標が達成されればOKとしませんか。

私もわからないことが多いですのでね、コントリビューターのみなさんの意見を聞きながらやっている感じです。

2021-01-19 08:19 UTC, mcdmaster commented on components/AppLink.vue
> +const options: NuxtConfig = {
@kaizumaki  はい、基本、下記方針に同意です。

> このPRについては最小限の変更にとどめていただいて、ogpのdescriptionに更新日時が反映されるという当初の目標が達成されればOKとしませんか

あえて詳細を付記すれば、上記目標を達成する際にタイトルだけ見えたり逆に違う設定をするとイメージだけ見えたりとなんだか不可思議（？）な現象が現れたため、ええいいっそ全部新しい方に寄せちまえ！と企図したという背景があります。
正直、FB シェアデバッガも疑いましたよ。ページロードの途中でリザルト出してるんとちゃうかと(笑)

いずれにせよ、私も、誰をも幸せにしない「金メッキ（gold plating）」を作るつもりは端からありませんので、 #5421 で問題になったポイントの解決に絞ることとします。アドバイスありがとうございます。しばしお時間をください

2021-01-19 16:07 UTC, mcdmaster commented on components/AppLink.vue
> +const options: NuxtConfig = {
やってみました。FB シェアデバッガ URL（再掲）はこちら。
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-5855--dev-covid19-tokyo.netlify.app%2Fcards%2Fnumber-of-confirmed-cases%2F

`pages/cards/_cards.vue` だけの修正で、当初は乗り切れると思っていました。
結果としては、options の平仄を合わせる（？）ため、親コンテナの `layouts/default.vue` も直さねばなりませんでした

2021-01-20 23:35 UTC, kaizumaki requested changes
かなりよくなってきましたね！
metaタグの `name` と `property` の使い分けと、ogpImageの三項演算子のところにコメントしました。
（`property` を使うのは `og:~` だけのようです）

2021-01-20 23:35 UTC, kaizumaki commented on pages/cards/_card.vue
> +      (this.$i18n.locale ?? 'ja-JP') === 'ja-JP'
ここの書き方が効いていないような気がします。
`??` ってC#, PHPの書き方ではないですかね？
`this.$i18n.locale === 'ja'` にしてもらうとよいかと思うのですが、いかがでしょう？

2021-01-20 23:35 UTC, kaizumaki commented on layouts/default.vue
> +          property: 'author',
ここは `name` のほうがよさそうです。
（参考：https://qiita.com/kana-t/items/76d84fb7746ed9c18d9d）

2021-01-20 23:35 UTC, kaizumaki commented on layouts/default.vue
> +          property: 'description',
ここも `name` ほうがよいかと思います。

2021-01-20 23:35 UTC, kaizumaki commented on layouts/default.vue
> +          property: 'apple-mobile-web-app-title',
ここも `name` ほうがよいかと思います。

2021-01-20 23:35 UTC, kaizumaki commented on layouts/default.vue
> +          property: 'twitter:image',
ここも `name` ほうがよいかと思います。

2021-01-20 23:35 UTC, kaizumaki commented on pages/cards/_card.vue
> +          property: 'description',
ここも `name` ほうがよいかと思います。

2021-01-20 23:35 UTC, kaizumaki commented on pages/cards/_card.vue
> +          property: 'twitter:image',
ここも `name` ほうがよいかと思います。

2021-01-21 01:33 UTC, mcdmaster commented on pages/cards/_card.vue
> +      (this.$i18n.locale ?? 'ja-JP') === 'ja-JP'
Nullish Coalescing Operator といい、TS 3.7 から使えるようになったみたいですよ
https://www.typescriptlang.org/play#example/nullish-coalescing

2021-01-21 01:34 UTC, mcdmaster commented on components/AppLink.vue
> +const options: NuxtConfig = {
具体的なレビューポイントのご指摘を頂戴しましたので、このスレッドはいったんクローズします

2021-01-21 01:39 UTC, kaizumaki commented on pages/cards/_card.vue
> +      (this.$i18n.locale ?? 'ja-JP') === 'ja-JP'
おお、なるほどです！では `ja-JP` を `ja` にする感じですかね。

2021-01-21 01:53 UTC, mcdmaster commented
レビューコメント反映後の、FB シェアデバッガのスクショです

![スクリーンショット 2021-01-21 105203](https://user-images.githubusercontent.com/10361533/105269201-d33c3780-5bd6-11eb-9396-d0162a83dbe5.png)

2021-01-21 12:31 UTC, kaizumaki approved these changes
よさそうですね！ご対応いただきありがとうございます。LGTM!

2021-01-21 13:46 UTC, mcdmaster commented
こちらこそありがとうございます！

本 PR は、いくつかのコンセプト・チェンジ、あるいはパラダイム・シフトをもたらしたと勝手に思っています。
これの横展開を図る PR を、遠くない先に出していこうと考えています

2021-01-22 06:18 UTC, merged

2021-01-22 08:30 UTC, kaizumaki commented
@mcdmaster すみません！nodeのバージョンを上げたところ、typeエラーを吐くようになってしまいました。一回マージしたのですがリバートさせていただきます 🙏