Gマークの画像から受賞理由が記載されたWebサイトへリンクする
tokyo-metropolitan-gov/covid19 pull request #5894
Opened 2021-01-14 10:24 UTC by nard-tech

## 👏 解決する issue / Resolved Issues
- close #5893

## 📝 関連する issue / Related Issues
- issue: #5884, #5892
- PR: #5885, #5889

## ⛏ 変更内容 / Details of Changes
- Gマークの画像に https://www.g-mark.org/award/describe/51112 へのリンクを追加する

2021-01-15 08:21 UTC, kaizumaki requested changes
日本デザイン振興会から許可がおりました！
１点コメントさせていただきましたので、ご対応よろしくお願いします 🙏

2021-01-15 08:21 UTC, kaizumaki commented on components/SideNavigation.vue
> -        <div class="SideNavigation-GMark">
ここの `div` はイキでお願いしたいのです。Gマークの周辺には余白が必要なため、marginをとっています。
あるいは `.SideNavigation-GMark` のcssに `display:block;` を追加するか、どちらかでお願いします 🙏

2021-01-18 09:40 UTC, nard-tech commented on components/SideNavigation.vue
> -        <div class="SideNavigation-GMark">
@kaizumaki 修正しました．ご確認お願いします．

2021-01-19 03:52 UTC, kaizumaki commented on components/SideNavigation.vue
> -        <div class="SideNavigation-GMark">
ああー、すみません！aタグを `display:block;` にしたいのですが、これだとimgにcssがかかっているんですね。私の見落としでした。やはり `div` で囲う方向で修正してもらえるでしょうか 🙏

2021-01-20 23:38 UTC, kaizumaki commented on components/SideNavigation.vue
> -        <div class="SideNavigation-GMark">
@nard-tech こちら `<div class="SideNavigation-GMark">` を復活してもらえますか 🙏 いまだとフォーカスのあたりかたがおかしくなっています。

2021-01-21 09:28 UTC, nard-tech commented on components/SideNavigation.vue
> -        <div class="SideNavigation-GMark">
@nard-tech すみません，margin の部分にリンクがきいてしまっていますね．修正しました．

2021-01-21 09:29 UTC, nard-tech commented on components/SideNavigation.vue
> -        <div class="SideNavigation-GMark">
`SideNavigation-GMark` は本来画像に付与するべきクラス名だと思うので，`SideNavigation-GMarkWrapper` に改めました．

2021-01-21 11:17 UTC, kaizumaki approved these changes
ご対応ありがとうございます！LGTM!

2021-01-22 06:12 UTC, merged