サイドメニュー内のソーシャルメディアへのリンクを ul, li タグでマークアップする
tokyo-metropolitan-gov/covid19 pull request #6428
Opened 2021-06-10 13:09 UTC by nard-tech

## 👏 解決する issue / Resolved Issues
- close #6409

## ⛏ 変更内容 / Details of Changes
- ソーシャルメディアへのリンクを ul, li タグでマークアップした

## 📸 スクリーンショット / Screenshots
見た目の変更はなし

2021-06-10 13:56 UTC, kaizumaki requested changes
こちらのプレビューだとアイコンがカラム落ちしてしまっています。現在の本番サイトを再現するために、いくつかコメントしました。ご確認いただけると助かります。
![スクリーンショット 2021-06-10 22 52 35](https://user-images.githubusercontent.com/14883063/121537563-ff9a0880-ca3e-11eb-8521-d766f560fbeb.png)

2021-06-10 13:56 UTC, kaizumaki commented on components/_shared/SideNavigation.vue
> +          <ul class="SideNavigation-Social clearfix">
```suggestion
          <ul class="SideNavigation-Social">
```

display:flexにすれば`clearfix` がなくても大丈夫だと思います。

2021-06-10 13:56 UTC, kaizumaki commented on components/_shared/SideNavigation.vue
>    display: flex;
```suggestion
```

ここの `display:flex;` は不要になるはずです。

2021-06-10 13:56 UTC, kaizumaki commented on components/_shared/SideNavigation.vue
> +    flex-direction: row;
```suggestion
```

ここも不要かと思われます。 `.SideNavigation-Footer-Rows` のdivがいらなくなると思います。

2021-06-10 13:56 UTC, kaizumaki commented on components/_shared/SideNavigation.vue
> +    .SideNavigation-Social {
```suggestion
    .SideNavigation-Social {
      display: flex;
```

`display:flex;` にすると何かと楽です。

2021-06-10 13:56 UTC, kaizumaki commented on components/_shared/SideNavigation.vue
> +        display: inline-block;
```suggestion
```

この２つは不要になると思います。

2021-06-20 15:32 UTC, nard-tech commented
@kaizumaki ご無沙汰しております．時間がとれず申し訳ありませんでした．
既存のページと同じ挙動を実現するために大幅に修正し，HTML の構造も `a` タグの位置を変えるなど変更しました．
ご確認お願いします．

2021-06-20 15:34 UTC, nard-tech commented on components/_shared/SideNavigation.vue
> +        margin-left: 12px;
DOM ツリーで `a.SideNavigation-SocialLink` の位置が変わったため，左右の border に相当する 1px * 2 を追加し現行のページと同じ見た目になるようにした．

2021-06-20 22:24 UTC, kaizumaki requested changes
いくつかコメントしました。ご確認いただけると助かります 🙏

2021-06-20 22:24 UTC, kaizumaki commented on components/_shared/SideNavigation.vue
> +            />
いま、これだと、aタグの中身がなくなってしまっています。現行の通り、`picture` を `app-link` の中に入れたほうがいいかと思うのですが、いかがでしょう？

2021-06-20 22:24 UTC, kaizumaki commented on components/_shared/SideNavigation.vue
> +        height: 100%;
`picture` を `a` タグの中に入れれば、ここのスタイルは不要になると思います。

2021-06-20 22:24 UTC, kaizumaki commented on components/_shared/SideNavigation.vue
> +      position: relative;
`picture` を `a` タグの中に入れれば、ここのスタイルは不要になると思います。

2021-06-21 10:26 UTC, nard-tech commented
@kaizumaki すみません，私の説明が不足していましたが，`ul > li > a > picture` という入れ子構造にすると，`a:focus` に対して設定される border が円ではなくなってしまい，`a` の領域も正方形ではなくなってしまうため，やむを得ず `a` と `picture` を並べ，`a` に `position: absolute` を設定して `picture` の領域全体を `a` がカバーするようにしています．
 
<img width="1291" alt="スクリーンショット 2021-06-21 19 22 52" src="https://user-images.githubusercontent.com/23148331/122747598-39340480-d2c6-11eb-93f7-73c7a3c2a23d.png">

2021-06-21 12:26 UTC, kaizumaki commented
@nard-tech 私もこのPRを手元に引っ張ってきて試してみましたが、 `ul > li > a > picture` でも問題ないですよ！私が提案したスタイル https://github.com/tokyo-metropolitan-gov/covid19/pull/6428#discussion_r654996718 https://github.com/tokyo-metropolitan-gov/covid19/pull/6428#discussion_r654996744 に加えて、 `.SideNavigation-SocialLink` を `display: block;` としたら現行通りになるはずです。

2021-06-21 13:53 UTC, nard-tech commented
@kaizumaki ご指摘のとおりにしたらうまくいきました．ありがとうございました．

2021-06-22 01:00 UTC, kaizumaki approved these changes
ご対応ありがとうございます！LGTM!

2021-06-22 05:09 UTC, merged