update staying population dayly to weekly.
tokyo-metropolitan-gov/covid19 pull request #6444
Opened 2021-06-18 05:37 UTC by tmatsuno

## 👏 解決する issue / Resolved Issues
- close #6443 

## ⛏ 変更内容 / Details of Changes

- 都内の滞在人口の増減状況（人流）を週一更新に改修

## 📸 スクリーンショット / Screenshots

<img width="547" alt="スクリーンショット 2021-06-18 14 36 26" src="https://user-images.githubusercontent.com/1682239/122511726-aafc1c00-d042-11eb-82e1-0295e0c52f82.png">

2021-06-18 08:59 UTC, kaizumaki approved these changes
LGTMです！

2021-06-20 15:43 UTC, nard-tech requested changes
コメントしました．ご確認お願いします．

2021-06-20 15:43 UTC, nard-tech commented on components/index/SiteTopUpper/StayingPopulation.vue
> +          {{ $t('都内の滞在人口の増減状況（毎週月曜日更新）') }}
```suggestion
          {{ $t('都内の滞在人口の増減状況')}}{{ $t('（毎週月曜日更新）') }}
```
と分割しておいた方が，更新のタイミングが変わる場合に「都内の滞在人口の増減状況」が翻訳されない事態を防げるのでよいと思います．

2021-06-20 22:41 UTC, kaizumaki commented on components/index/SiteTopUpper/StayingPopulation.vue
> +          {{ $t('都内の滞在人口の増減状況（毎週月曜日更新）') }}
フォローありがとうございます！これなのですが、翻訳時に文脈がわかるようになるべくセンテンスは分けずにおいています（特に英訳で、意味が通じない、テキストの体裁が合わない、などの不具合が生じたため）。ここの場合は、判断は別れるところではあると思うのですが、現在の運用上（古い翻訳キーを削除しない）、当面は翻訳されない事態は起きないと思われるので、こちらのPRは変更せずにいきたいと思います。

2021-06-21 05:31 UTC, merged

2021-06-21 09:45 UTC, nard-tech commented on components/index/SiteTopUpper/StayingPopulation.vue
> +          {{ $t('都内の滞在人口の増減状況（毎週月曜日更新）') }}
@kaizumaki 承知しました．ありがとうございます．