Feat/pw2vw
tokyo-metropolitan-gov/covid19 pull request #6452
Opened 2021-06-21 03:47 UTC by mcdmaster

## 👏 解決する issue / Resolved Issues
- #6346 (Partially)

## 📝 関連する issue / Related Issues
- #6420
- #6417
- #6380

## ⛏ 変更内容 / Details of Changes

- Modify `assets/monitoringItemsTableCommon.scss` (割り算方法の変更を含む：一部 #6346 とカブります)
- Modify references (quite few or none)
- Own-coded scss changed to referreing above: `components/index/CardsMonitoring/ConfirmedCasesDetails/Table.vue`
- Update `SASS` module and `yarn.lock` / `packages.json` accordingly 

## 📸 スクリーンショット / Screenshots

たぶん、変化はありません。為念
![スクリーンショット 2021-06-21 124433](https://user-images.githubusercontent.com/10361533/122704335-78466380-d28e-11eb-8c52-0363f2892b48.png)

2021-06-21 11:49 UTC, kaizumaki requested changes
いやあ、実に見事です。ご対応ありがとうございます！
#6420 がマージできそうなので、このPRのpackage.jsonからはsassをremoveしてもらえるとよいかと思います！

2021-06-21 11:49 UTC, kaizumaki commented on stylelint.config.js
> +        patterns: ['$num * 100000vw'],
すみません、ちょっと教えてください！ここってどういう意味なんでしょう...？

2021-06-21 11:49 UTC, kaizumaki commented on package.json
> +    "sass": "1.35.1",
sassを改めてインストールしなくても、#6420 をマージすればいけるはずですよね。

2021-06-21 12:41 UTC, mcdmaster commented on stylelint.config.js
> +        patterns: ['$num * 100000vw'],
@kaizumaki 

たぶん[このあたり](https://stylelint.io/user-guide/rules/list/function-calc-no-invalid/)を引いてくると、説明が長くなってしまうと思います。
私なりの解釈では、たとえば `Dart SASS` 以前に広く使われていたであろう `node-sass` は比較的シンタックス・チェックが甘く、逆に `Dart` の方はえらい厳しいという見方をしています。
その、えらく厳しいチェックを特定の用途のためにバイパスするのが `function-calc-no-invalid` という `stylelint` オプションです。とはいえ、`math.div` の件もそうですけど、自分で自分の首を絞める的なアプローチってそもそもどうなんだろう…という素朴な疑問はありますｗ

2021-06-21 12:42 UTC, mcdmaster commented on package.json
> +    "sass": "1.35.1",
はい、外しましょう

2021-06-21 22:55 UTC, kaizumaki commented
ご対応ありがとうございます！現在、yarn.lockがいろいろ巻き込んじゃっているみたいなので、いったんこちらで引き取らせてください。

2021-06-21 23:08 UTC, mcdmaster commented
@kaizumaki お手数を掛けます！どうか宜しくお願いいたします。
さすがに conflict を残しておくのは気持ち悪かったので、取ってしまいました

2021-06-22 05:20 UTC, mcdmaster commented
Closed since handover to #6459 is complete. Thank you!

2021-06-22 05:33 UTC, kaizumaki commented
@mcdmaster クローズしてもらったところ、申し訳ないですが、やはりこちらのPRはうまくいっていないようです。mathの `div` が文字列としてそのまま出力されてしまっています。

![スクリーンショット 2021-06-22 14 30 03](https://user-images.githubusercontent.com/14883063/122868961-89fb3a00-d366-11eb-86ab-5e973396ba7f.png)

おそらく、webpackのloaderあたりがうまく動いていないんじゃないかと思っています。私のほうでも調べてみます。
こちらのPRは念のため再オープンしておきますね。

2021-06-22 07:49 UTC, kaizumaki commented
dart sassの公式のドキュメントによると、`math.div` はsass 1.33.0からのサポートであり、一方でVuetifyはsassのバージョンを1.32に落とさないとワーニングが止まらなくなってしまうのですよね。なので、実質sassは1.32を使わざるを得なく、よって `math.div` は使えない、ということのようです。試しに1.25.0からサポートされている `math.pow` に変えてみたら、ちゃんと動作しました。
すべてはVuetifyの対応を待ってから、というほうがよさそうです。

![スクリーンショット 2021-06-22 16 41 36](https://user-images.githubusercontent.com/14883063/122885033-a94f9280-d379-11eb-9ff7-8326623901a1.png)

2021-07-01 07:20 UTC, mcdmaster commented
@kaizumaki もしかしたら効率的な修正じゃないかも…と思いつつ、 `assets/monitoringItemsTableCommon.scss` へ大幅に手を入れてみました。スクショもつけておきますので、おおよそこんなかんじになるかと
![スクリーンショット 2021-07-01 132418](https://user-images.githubusercontent.com/10361533/124082831-1f45af00-da88-11eb-9dd7-43651685a999.png)

2021-07-02 02:03 UTC, kaizumaki commented
@mcdmaster おお、これはまたすごいですね！math.divを条件分岐する作戦ですね。
プレビューを拝見したところ、どこかがバグってしまっているようです。
- デスクトップサイズ時
![スクリーンショット 2021-07-02 10 56 44](https://user-images.githubusercontent.com/14883063/124209464-8e70e100-db24-11eb-81bf-8599cfddb308.png)

- モバイルサイズ時
![スクリーンショット 2021-07-02 10 49 21](https://user-images.githubusercontent.com/14883063/124209510-a21c4780-db24-11eb-92e6-6dfe5a4e5d64.png)

そしておそらく、math.divが使用されるためにはsassを1.33.0以上にアップデートしないといけないですよね。その判断もまたVuetifyの対応次第ということになりますが...

2021-11-15 07:45 UTC, kaizumaki commented
@mcdmaster 引き続きフォローいただいているところすみません、 `.eslintrc.cjs` って必要なのでしょうか...？ `.cjs` ってサーバーサイドのモジュールだと思うのですが、フロントでは必要なかったりしませんかね？

2021-11-15 08:10 UTC, mcdmaster commented
@kaizumaki 、各位
ダラダラと合間を縫って更新しているため、メールがたくさん飛んでいるかと存じます。
ご迷惑を掛けています。なかなか‘ eslint が通らなくってですね…。

で、ご指摘のように、クライアント主体であれば .eslintrc は要らなくなってくるのでしょう。
ただ、私自身詳しいわけではけしてないので、サーバサイドで lint をせずに済む仕組みに向けたロードマップがどうなるのか、まるでわかりません。
そんな状況下で、サーバ・クライアントの区別に依存しなくても実行できる「構文チェック」ツールとしては、lint の強みは失われていないと思います

2021-11-15 08:13 UTC, kaizumaki commented
@mcdmaster すみません、私がちょっと言葉足らずでした。 `.eslintrc.cjs` ではなくて `.eslintrc.js` は必要だと思っています。

2021-11-15 17:22 UTC, mcdmaster commented
@kaizumaki 私の認識は、`cjs, mjs` といったファイル形式は単にスクリプトとしての `Javascript` からのモジュール形式への進化のようなものをレペゼン（represent）する、といものでした。
ですので、クライアント用、サーバ用、といった区別をそこでしたことは、私に限って言えばありませんね。
今回においても、`.eslintrc.cjs` と `.eslintrc.js` ファイルは併存できないと思います

2021-11-20 22:18 UTC, mcdmaster commented
突然ながら、こちら、取り下げます。理由は、以下によります

- 元々は、`SASS` のロードマップで今後 / （フォワードスラッシュ）記号を CSS コード中の除算処理に使えなくなるとのリリースが出たため、それへの対処が必要とされたことによる
- 現時点で、`SASS` のバージョンを固定化することで対処している
- 対処内容は、アプリの側が `SASS` 推奨の除算記法 `math.div(y, x)` に未対応の場合、ビルド時に著しく大量に出力されるワーニング・ログ・メッセージの抑制である
- `SASS` は、アップグレードへの注意を促すために必要だからやっているいることで、ログ出力の抑制方法は提供しないという立ち位置である
- ビルド時は `node_modules` の中まで走査がされるため、特にそこにある `Vuetify` の `SASS` コンポーネントが軒並みワーニング対象となってしまう
- いずれにしても、セキュリティ対応等の観点からは、現行の `SASS` バージョンにピン（固定化）するのでなく、アップグレードが必要になってくるだろう
- これに合わせ、プラットフォームやコンポーネントの最新化を図るためには、可能な限り包括的、複合的にことを進めた方が効率的に思われる
- じっさい、`SASS` メッセージの抑制という一見シンプルな要件への対応を試みたところ、影響範囲を考えるとかなりの手間を割くことが判明した
- これでは「割に合わない」ため、いったん顔を洗って出直すこととする

いささか身勝手ではありますけれども、事情をご斟酌いただけますと幸いです。
なお、ごくコンパクトにまとめた、他のアプリへの影響等を一切捨象したミニ・バージョンを、Tips&Tricks と備忘の意味で公開するかもしれません。
そのときは、同じ事情で苦しんでいる海外の開発者からも参照されるよう、可能な限り英文で書いていきます

2021-11-20 22:18 UTC, closed without merging