サイトマップページを追加
tokyo-metropolitan-gov/covid19 pull request #6551
Opened 2021-07-27 03:51 UTC by kaizumaki

## 👏 解決する issue / Resolved Issues
- close #6411 

## ⛏ 変更内容 / Details of Changes

- サイトマップのページを追加しました
- cardのpathなど、共通で使えるようにjsonにまとめました

## 📸 スクリーンショット / Screenshots

![スクリーンショット 2021-07-27 12 50 54](https://user-images.githubusercontent.com/14883063/127092549-d4728edd-3b72-4340-8b23-65201d7143e8.png)

2021-07-27 04:15 UTC, kaizumaki commented
@magi1125 こちらレビューしてもらえると助かります！ 🙏

2021-07-27 10:24 UTC, magi1125 approved these changes
LGTMです!

2021-09-06 03:51 UTC, Murayu0225 requested changes

2021-09-06 03:59 UTC, kaizumaki commented on ui-test/ogp_screenshot.py
> +f = open('../assets/json/cardRoutesSettings.json', 'r')
おお！フォロー＆検証ありがとうございます！修正取り入れさせてください 🙏

2021-09-23 08:27 UTC, kaizumaki commented
現在のコンテンツに合わせて修正しました。

![スクリーンショット 2021-09-23 17 25 55](https://user-images.githubusercontent.com/14883063/134476202-0c47342b-67aa-4418-bce0-28487f45a227.png)


「報告日別による陽性者数（65歳以上）の推移」カードのパーマリンクの設定が間違っていたので合わせて修正しました。

2021-09-24 04:57 UTC, soutaito approved these changes
LGTM!

2021-09-24 04:57 UTC, merged