migrate nuxt-i18n to @nuxtjs/i18n
tokyo-metropolitan-gov/covid19 pull request #6576
Opened 2021-08-04 17:08 UTC by mcdmaster

## 👏 解決する issue / Resolved Issues
- close #6575 

## 📝 関連する issue / Related Issues
- N/A

## ⛏ 変更内容 / Details of Changes

- `package.json` で、`nuxt-i18n` エントリを `@nuxtjs/i18n` に差し替え
- コンフィグ系ファイルの修正（`nuxt.config.ts`, `tsconfig.json` など）
- アプリの修正（`pages/layout.vue`）
- `yarn.lock` の更新

## 📸 スクリーンショット / Screenshots

(原則、アピアランスの変更は一切ありません)

2021-08-24 11:09 UTC, MaySoMusician requested changes
お久しぶりです。ついにnuxt公式のモジュールになるのですね。
実はまだコードは手元で動かしていないのですが、[移行ガイド](https://i18n.nuxtjs.org/migrating)を読んだ限りで気になるところをピックアップしました。

2021-08-24 11:09 UTC, MaySoMusician commented on layouts/default.vue
> +    const { htmlAttrs, meta } = {} as MetaInfo
[移行ガイド](https://i18n.nuxtjs.org/migrating#nuxti18nseo-has-been-removed)によると、 `$nuxtI18nSeo()` は `$nuxtI18nHead({ addSeoAttributes: true })` で代用するらしいので、ここはそれを使ったほうがいいと思います（現在の提案だと `htmlAttrs` と `meta` が undefined になってしまうので、もともとの動作と一致しないかと）

[ここ](https://i18n.nuxtjs.org/seo/#setup) の2個めのサンプルも参考になるかと思います

2021-08-25 08:22 UTC, mcdmaster commented on layouts/default.vue
>    head() {
@MaySoMusician 本当にお久しぶりです(笑)

まず、アドバイスありがとうございます。いただいたご指摘を参考にしつつ、私の方でもいろいろ調べてみたところ、今時点の最新コミット版の `layouts/defaut.vue` の書き方で `{ htmlAttrs, meta }` を初期化するのが良いという判断をしました。
最も大きな理由は、`@nuxtjs/i18n` に絞った環境で `$nuxtI18nOptions()` が使えない、具体的には、アプリが `$nuxtI18nOptions is undefined` とエラーを吐いて立ち上がらないという大きな問題がありました。
そこで、最新コミット版の内容を適用したという顛末になります。ぜひ、再レビューをいただきたく

2021-08-25 08:24 UTC, mcdmaster commented on layouts/default.vue
> +    const { htmlAttrs, meta } = {} as MetaInfo
これのリプライで修正コードを引っ張ってくるやり方が判然としなかったため、別コメントを記載しています。
それに伴い、こちらはいったん Resolved ステータスにさせていただきたく

2021-08-25 08:27 UTC, mcdmaster commented
なんだか、Netlify がおかしなエラーを吐いて先に進めませんね。下に抜粋しましたので、ご確認ください。
私は初見のエラーなので、少し戸惑っています。うーん

`
5:03:00 PM: Installing gem bundle
5:03:00 PM: [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path '/opt/build/cache/bundle'`, and stop using this flag
5:03:01 PM: [DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
5:03:02 PM: Fetching gem metadata from https://rubygems.org/.........
5:03:03 PM: Your bundle is locked to parallel (1.20.2), but that version could not be found
5:03:03 PM: in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of parallel (1.20.2) has removed it. You'll need to update
your bundle to a version other than parallel (1.20.2) that hasn't been removed
in order to install.
5:03:03 PM: Error during gem install
5:03:03 PM: Build was terminated: Build script returned non-zero exit code: 1
5:03:03 PM: Creating deploy upload records
5:03:03 PM: Failing build: Failed to build site
5:03:03 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
5:03:03 PM: Finished processing build request in 1m21.452896202s
`

2021-08-25 10:23 UTC, kaizumaki commented
> なんだか、Netlify がおかしなエラーを吐いて先に進めませんね。下に抜粋しましたので、ご確認ください。
> 私は初見のエラーなので、少し戸惑っています。うーん

どうやらrenovateの Lock file maintenance #6671 をマージしていなかったのが原因かと思われます。
一度、空コミットしてCIを再起動してみてもらえますか？お手数おかけします 🙇‍♀️

2021-09-06 08:15 UTC, MaySoMusician requested changes
ありがとうございます。確認しました
いくつかrequest changesしましたのでご確認ください（一応こちらのローカルでは動きました）

もし VS CodeなどでTypeScriptのインテリジェンスがうまく機能しない場合は、 `types/shims-vue.d.ts` の1行目に `export {}` を入れてみてください（リロードする必要があるかも）
（こちら、.d.tsの記述ミスなのですが別PRで扱います）

2021-09-06 08:15 UTC, MaySoMusician commented on layouts/default.vue
> +import { NuxtConfig, NuxtOptionsHead as MetaInfo } from '@nuxt/types'
```suggestion
import type { NuxtOptionsHead as MetaInfo } from '@nuxt/types/config/head'
import type { NuxtConfig } from '@nuxt/types'
import type { LinkPropertyHref } from 'vue-meta'
```
`NuxtOptionsHead` は `@nuxt/types` には無さそうなので別途引っ張ってくる必要がありそうです。  `LinkPropertyHref` についても `vue-meta` のを使いたい（より定義が細かいので）

2021-09-06 08:15 UTC, MaySoMusician commented on layouts/default.vue
>      type LinkPropertyHref = typeof htmlAttrs
上でimportしたのでここが不要になります
```suggestion
```

2021-09-06 08:15 UTC, MaySoMusician commented on nuxt-i18n.config.ts
> +import { NuxtAppOptions, NuxtConfig } from '@nuxt/types'
```suggestion
import type { NuxtConfig } from '@nuxt/types'
import type { DateTimeFormat } from 'vue-i18n'
```
`@nuxtjs/i18n` がオプションのinterfaceをNuxtConfigにマージしてくれているようなので、そこ経由で使います
`DateTimeFormat` は `dateTimeFormatsCommon` の各オプションをstringではなく定義されたリテラルとして認識させるために使います

2021-09-06 08:15 UTC, MaySoMusician commented on nuxt-i18n.config.ts
>  const dateTimeFormatsCommon = {
```suggestion
const dateTimeFormatsCommon: DateTimeFormat = {
```

2021-09-06 08:15 UTC, MaySoMusician commented on nuxt-i18n.config.ts
> +export default options as NuxtAppOptions
```suggestion
export default options
```
`as XXX` にすると型チェックが利かなくなる場合があるので、32行目あたりの代入時に型を指定します

```diff
- const options: NuxtConfig = {
+ const options: NuxtConfig['i18n'] = {
```

2021-09-06 08:15 UTC, MaySoMusician commented on utils/i18nUtils.ts
> +import type { NuxtOptionsHead as MetaInfo } from '@nuxt/types/config/head'
```suggestion
import { LinkPropertyHref } from 'vue-meta'
```
eslintの `import/named` のエラーがでますがここは元のままでよいようです

2021-09-06 08:15 UTC, MaySoMusician commented on utils/i18nUtils.ts
> +  type LinkPropertyHref = MetaInfo
```suggestion
```
`vue-meta`から取ってくるので不要になります

2021-09-06 08:15 UTC, MaySoMusician commented on utils/i18nUtils.ts
> +      } as MetaInfo)
```suggestion
      })
```
importを直すとここが無くても通るはずです

2021-09-06 08:15 UTC, MaySoMusician commented on utils/i18nUtils.ts
> +    } as MetaInfo)
```suggestion
    })
```
32行目あたりに同じ

2021-09-06 08:15 UTC, MaySoMusician commented on layouts/default.vue
> +    const { htmlAttrs, meta } = { addSeoAttributes: true } as MetaInfo
```suggestion
    const { htmlAttrs, meta } = this.$nuxtI18nHead({ addSeoAttributes: true })
```
このように使うとよいらしいです（移行ガイド）

2021-09-06 19:33 UTC, mcdmaster commented
@MaySoMusician レビューありがとうございます！
いただいたレビューコメントに特に異論はなかったため、原則全てコミットさせていただきました。
ご確認をお願いいたします

2021-09-07 02:47 UTC, MaySoMusician requested changes
ありがとうございます！ 確認しました。
そのうえで、いくつかこちらで変更依頼が漏れていた部分がありました。お手数おかけしますが再度確認いただければ幸いです。

GitHubの仕様でコメントが書けないのが1個あるのでこちらに書きます。手動で反映お願いします。

`nuxt-i18n.config.ts` の33行目
```diff
- const options: NuxtConfig = {
+ const options: NuxtConfig['i18n'] = {
```

2021-09-07 02:47 UTC, MaySoMusician commented on types/shims-vue.d.ts
>  declare module 'vue/types/vue' {
```suggestion
export {}
declare module 'vue/types/vue' {
```
ここ、1行目に `export {}` 追加お願いします（詳しい説明は割愛しますが、1行目のやつが無いと Vue への inject 関連がうまく動かないのです）

2021-09-07 02:47 UTC, MaySoMusician commented on nuxt-i18n.config.ts
>    seo: false,
```suggestion
```
この seo オプションは @nuxtjs/i18n では無くなったので削除。

2021-09-07 02:48 UTC, MaySoMusician commented
@mcdmaster 重ねて、コンフリクトも解消していただければと思います！

2021-09-08 04:37 UTC, MaySoMusician commented on utils/i18nUtils.ts
> +import LinkPropertyHref from 'vue-meta'
```suggestion
import { LinkPropertyHref } from 'vue-meta' // eslint-disable-line import/named
```
ここは #6721 にあわせて一旦これでお願いします！

2021-09-08 05:30 UTC, mcdmaster commented on utils/i18nUtils.ts
> +import LinkPropertyHref from 'vue-meta'
対応しました～

2021-09-08 07:25 UTC, MaySoMusician approved these changes
確認しました、LGTMです！

2021-09-08 07:25 UTC, merged

2021-09-08 08:45 UTC, mcdmaster commented
ありがとうございました！