「相談の手順を見る 」のコーナーを「新型コロナ保健医療情報ポータル」に変更
tokyo-metropolitan-gov/covid19 pull request #6614
Opened 2021-08-18 15:10 UTC by knknk98

## 👏 解決する issue / Resolved Issues
- close #6611 

## ⛏ 変更内容 / Details of Changes

ファーストビュー内「自分や家族の症状に不安や心配があればまずは電話相談をどうぞ」のブロックを以下に変更しました。

テキスト：ワクチン情報・変異株情報・検査情報等の新型コロナ関連情報はこちら
ボタンテキスト：新型コロナ保健医療情報ポータル
リンク先URL：https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/corona_portal/index.html

## 📸 スクリーンショット / Screenshots

![IMG_7345](https://user-images.githubusercontent.com/65712721/129923295-4f51702c-f7f1-44be-a094-406c3e2c0c67.JPG)

2021-08-19 00:30 UTC, kaizumaki requested changes
PRありがとうございます！１点コメントしました 🙇‍♀️

2021-08-19 00:30 UTC, kaizumaki commented on components/index/SiteTopUpper/Consultation.vue
> +            'ワクチン情報・変異株情報・検査情報等の\n新型コロナ関連情報はこちら'
```suggestion
            'ワクチン情報・変異株情報・検査情報等の新型コロナ関連情報はこちら'
```

`\n` は翻訳時の事故のもとなので 💦  入れなくて大丈夫です！
`\n` をとった上で、cssのほうを整えてもらえると助かります 🙏

2021-08-19 12:19 UTC, knknk98 commented on components/index/SiteTopUpper/Consultation.vue
> +            'ワクチン情報・変異株情報・検査情報等の\n新型コロナ関連情報はこちら'
@kaizumaki 
コメントありがとうございます！修正したものをpushしたのでご確認よろしくお願いします！

2021-08-19 20:53 UTC, kaizumaki commented on components/index/SiteTopUpper/Consultation.vue
> +            'ワクチン情報・変異株情報・検査情報等の\n新型コロナ関連情報はこちら'
@knknk98 ご対応ありがとうございます！
プレビュー見て思ったんですが、`flex-wrap: wrap;` を削除するだけだと、以下のようにブラウザ幅を狭くした際にちょっと見栄えが良くないのですよね...。

![スクリーンショット 2021-08-20 5 46 04](https://user-images.githubusercontent.com/14883063/130141821-37dc7961-2dc0-45bf-8f0f-677c97c09563.png)

.StaticInfoの `flex-wrap: wrap;` は削除せずに、
.StaticInfo-Textに以下を追記すると、程よいところで折り返してくれて、見栄えもよさそうです。
```
flex: 1 0 50%;
padding-right: 16px;
```
（padding-rightは、ボタンとの隙間を開けるために入れています）

ちょっと試してみてもらえると嬉しいです 🙏

2021-08-20 12:51 UTC, knknk98 commented on components/index/SiteTopUpper/Consultation.vue
> +            'ワクチン情報・変異株情報・検査情報等の\n新型コロナ関連情報はこちら'
@kaizumaki 
ありがとうございます！確かにブラウザ幅狭くした際に見栄えが良くなかったですね...。
.StaticInfoの`flex-wrap: wrap;`を削除せず.StaticInfo-Textに

```
flex: 1 0 50%;
padding-right: 16px;
```
を追加したのでご確認よろしくお願いします！

2021-08-20 13:17 UTC, kaizumaki commented on components/index/SiteTopUpper/Consultation.vue
> +            'ワクチン情報・変異株情報・検査情報等の\n新型コロナ関連情報はこちら'
プレビュー見ました！いいですね！ありがとうございます！

2021-08-31 01:20 UTC, merged