[Draft]「L452R変異株スクリーニングの実施状況」グラフ下に「変異株情報」ボタンを追加 #6680
tokyo-metropolitan-gov/covid19 pull request #6686
Opened 2021-08-28 21:42 UTC by edamame8888

## 👏 解決する issue / Resolved Issues
- close #6680

## 📝 関連する issue / Related Issues
- 「L452R変異株スクリーニングの実施状況」グラフ下に「変異株情報」ボタンを追加

## ⛏ 変更内容 / Details of Changes

- 「検査陽性者の状況」表の「死亡日別による死亡者数の推移はこちら」を参考に「L452R変異株スクリーニングの実施状況」グラフ下に「変異株情報」ボタンを追加
- Variantのチャートコンポーネント(`components/index/CardsReference/Variant/Chart.vue`)に名前付きスロット"additionalButton" を追加

## 📸 スクリーンショット / Screenshots

<img width="1434" alt="6680-add-henikabu-button-screenshot" src="https://user-images.githubusercontent.com/41494250/131231691-2e956984-2a6d-40c9-b1e8-56f85e649edd.png">

2021-08-28 23:49 UTC, kaizumaki requested changes
PRありがとうございます！
いくつかコメントしました。ご確認いただけると助かります！ 🙏

2021-08-28 23:49 UTC, kaizumaki commented on components/index/CardsReference/Variant/Chart.vue
> +    <slot name="additionalButton" />
```suggestion
    <template #additionalButton>
      <slot name="additionalButton" />
    </template>
```

これってお作法的にtemplateで囲む必要があるはずなんですよね。

2021-08-28 23:49 UTC, kaizumaki commented on components/index/CardsReference/Variant/Card.vue
> +            <span :class="$style.buttonInner">
```suggestion
            <span :class="$style['button-inner']">
```
実は `nuxt generate` でキャメルケースのclass名が効かないというワナがあって、いまnetlifyのプレビューでスタイルが崩れてしまっています。
上記のような書き方だとうまく通ります。

2021-08-28 23:49 UTC, kaizumaki commented on components/index/CardsReference/Variant/Card.vue
> +              <covid-icon :class="$style.buttonIcon" aria-hidden="true" />
```suggestion
              <covid-icon :class="$style['button-icon']" aria-hidden="true" />
```
こちらのキャメルケースも同様ですね。

2021-08-28 23:49 UTC, kaizumaki commented on components/index/CardsReference/Variant/Card.vue
> +  &Inner {
```suggestion
  &-inner {
```
class名の変更に合わせます。

2021-08-28 23:49 UTC, kaizumaki commented on components/index/CardsReference/Variant/Card.vue
> +  &Icon {
```suggestion
  &-icon {
```
class名の変更に合わせます。

2021-08-29 03:11 UTC, edamame8888 commented on components/index/CardsReference/Variant/Chart.vue
> +    <slot name="additionalButton" />
@kaizumaki 
レビューありがとうございます。
親コンポーネント(@/components/index/_shared/DataView.vue)の名前付きスロットにコンテンツを指定しているわけではないので、templateを使用していません。  
大変恐縮ですが、templateでslotを囲うべきという推奨ルール等あればリンク等教えていただけないでしょうか？

2021-08-29 03:12 UTC, edamame8888 commented on components/index/CardsReference/Variant/Card.vue
> +  &Icon {
@kaizumaki 
ご指摘ありがとうございます！
70ee00df4abd1ba0b8f9c9d9278e5759975029df にて修正しました！

2021-08-29 03:12 UTC, edamame8888 commented on components/index/CardsReference/Variant/Card.vue
> +  &Inner {
@kaizumaki 
ご指摘ありがとうございます！
70ee00df4abd1ba0b8f9c9d9278e5759975029df にて修正しました！

2021-08-29 03:12 UTC, edamame8888 commented on components/index/CardsReference/Variant/Card.vue
> +              <covid-icon :class="$style.buttonIcon" aria-hidden="true" />
@kaizumaki 
ご指摘ありがとうございます！
70ee00df4abd1ba0b8f9c9d9278e5759975029df にて修正しました！

2021-08-29 03:12 UTC, edamame8888 commented on components/index/CardsReference/Variant/Card.vue
> +            <span :class="$style.buttonInner">
@kaizumaki 
ご指摘ありがとうございます！
70ee00df4abd1ba0b8f9c9d9278e5759975029df にて修正しました！

2021-08-29 03:31 UTC, kaizumaki commented on components/index/CardsReference/Variant/Chart.vue
> +    <slot name="additionalButton" />
お、すみません、ああーなるほど `DataView.vue`に `additionalButton` というslotはないのですね。てっきりあるのかと思ってました。私の勘違いでした 🙇‍♀️  このままで大丈夫です！

2021-08-29 03:39 UTC, kaizumaki submitted a review, later dismissed
ご対応いただきありがとうございます！バッチリです！LGTM!

2021-08-29 03:47 UTC, edamame8888 commented
@kaizumaki　
マージ前に1点確認した遺ことがございます。

eslint で `import/named` ルールに引っかかっているのですが、こちらはこのままでもよろしいでしょうか？
```
  88:15  error  PropType not found in 'vue'              import/named
  90:10  error  TranslateResult not found in 'vue-i18n'  import/named
```

2021-08-29 03:51 UTC, kaizumaki commented
@edamame8888 お、やはりそれで引っかかってますか。私が自分で実装している分はとりあえず該当行に ` // eslint-disable-line import/named` を書いて逃げています。このPRでも同様に対応してもらっておいてもらえますか？（そもそものeslintルールについては別途考えたいと思います。）

2021-08-29 03:59 UTC, edamame8888 commented
```diff
- import Vue, { PropType } from 'vue'
- import { ThisTypedComponentOptionsWithRecordProps } from 'vue/types/options'
- import { TranslateResult } from 'vue-i18n'
+ import Vue from 'vue'
+ import {
+   PropType,
+   ThisTypedComponentOptionsWithRecordProps,
+ } from 'vue/types/options'
+ import VueI18n from 'vue-i18n'
```
`TranslateResult` は、`VueI18n.TranslateResult` でアクセスする。
ことでエラーは出力されないことを確認しました。
 
@kaizumaki さんのおっしゃる通り、まとめてESLintエラーの対応した方が良いと思うので、
`// eslint-disable-line import/named` で対応させていただきます。
よろしくお願いいたします。

2021-08-29 04:02 UTC, kaizumaki commented
調査ありがとうございます！ @edamame8888 さんの上記コメントを引用してissueを立てることにしますね！

2021-08-29 04:06 UTC, edamame8888 commented
> 調査ありがとうございます！ @edamame8888 さんの上記コメントを引用してissueを立てることにしますね！

@kaizumaki
もっとより良い対応があるかもしれませんが、お役に立ててよかったです。

a988a5a　にて`// eslint-disable-line import/named` の対応を行いました。

2021-08-29 04:11 UTC, kaizumaki approved these changes
ありがとうございます！

2021-08-31 01:29 UTC, merged