「死亡日別による死亡者数の推移」カードへ注釈を追加
tokyo-metropolitan-gov/covid19 pull request #6908
Opened 2021-10-30 05:21 UTC by Murayu0225

## 👏 解決する issue / Resolved Issues
- close #6905 

## ⛏ 変更内容 / Details of Changes

- 「死亡日別による死亡者数の推移」カードへ注釈を追加しました。追加した内容に関しては、 #6905 と同様なので省略します。

## 📸 スクリーンショット / Screenshots

2021-10-30 07:08 UTC, kaizumaki requested changes
ご対応ありがとうございます！１点コメントしました 🙏

2021-10-30 07:08 UTC, kaizumaki commented on components/index/CardsReference/DeathsByDeathDate/Card.vue
> +                <app-link to="/cards/details-of-confirmed-cases/">
```suggestion
                <app-link :to="localePath('/cards/details-of-confirmed-cases/')">
```

リンクをlocalePathで多言語化してもらえると助かります！

2021-10-30 10:04 UTC, Murayu0225 commented on components/index/CardsReference/DeathsByDeathDate/Card.vue
> +                <app-link to="/cards/details-of-confirmed-cases/">
ありがとうございます。
commitしました。

2021-10-30 10:12 UTC, kaizumaki commented on components/index/CardsReference/DeathsByDeathDate/Card.vue
> +                <app-link to="/cards/details-of-confirmed-cases/">
あ、すみません、prettierに引っかかったみたいです。lint通してもらえると嬉しいです。

2021-10-30 10:21 UTC, Murayu0225 commented
後程、eslintエラー対応します。

2021-10-31 00:29 UTC, Murayu0225 commented
lintエラー解決しました。
レビューお願いします。

2021-11-01 00:19 UTC, kaizumaki approved these changes
ご対応ありがとうございます！LGTM!

2021-11-01 00:24 UTC, merged