「L452R変異株スクリーニングの実施状況」カードにデータ更新終了のアナウンスを掲示
tokyo-metropolitan-gov/covid19 pull request #6934
Opened 2021-11-17 16:00 UTC by knknk98

## 👏 解決する issue / Resolved Issues
- close #6933 

## ⛏ 変更内容 / Details of Changes

- 「L452R変異株スクリーニングの実施状況」カードにデータ更新終了のアナウンスを掲示しました。
- `slot name="attentionNote"`に配置しました。

## 📸 スクリーンショット / Screenshots

<img width="552" alt="スクリーンショット 2021-11-18 0 58 54" src="https://user-images.githubusercontent.com/65712721/142235407-c85f9172-e211-42a0-a2f5-845afe8254de.png">

2021-11-17 22:31 UTC, kaizumaki requested changes
ご対応ありがとうございます！
なるほど、以前黄色のカラーコードをすべて変更したために、ここの部分もくすんだ黄色になってしまっているのですね。
この部分は前の黄色に戻したいので、お手数ですが以下の `assets/variables.scss` の `$notice: #B19201;` を `$notice: #FFDB1D;` にしてもらえるでしょうか？ 🙏 

https://github.com/tokyo-metropolitan-gov/covid19/blob/bf9173a1392f9776ce846e73ab9117eb380aca05/assets/variables.scss#L15

2021-11-18 00:29 UTC, knknk98 commented
> ご対応ありがとうございます！ なるほど、以前黄色のカラーコードをすべて変更したために、ここの部分もくすんだ黄色になってしまっているのですね。 この部分は前の黄色に戻したいので、お手数ですが以下の `assets/variables.scss` の `$notice: #B19201;` を `$notice: #FFDB1D;` にしてもらえるでしょうか？ 🙏
> 
> https://github.com/tokyo-metropolitan-gov/covid19/blob/bf9173a1392f9776ce846e73ab9117eb380aca05/assets/variables.scss#L15

レビューありがとうございます！カラーコードを変更したものをpushしたのでご確認よろしくお願いします！

2021-11-18 00:46 UTC, kaizumaki submitted a review, later dismissed
ありがとうございます！LGTM!

2021-11-18 01:58 UTC, kaizumaki commented on components/index/CardsReference/Variant/Card.vue
> +              '全国的にデルタ株に置き換わったこと等の理由により、厚生労働省から全ての自治体におけるL452R変異株PCR検査を終了する方針が示されたことに伴い、都モニタリング会議におけるL452R変異株スクリーニング検査の報告が終了したことから、同年11月11日（木曜日）をもって本グラフの数値更新を終了しました。'
```suggestion
              '全国的にデルタ株に置き換わったこと等の理由により、厚生労働省から全ての自治体におけるL452R変異株PCR検査を終了する方針が示されたことに伴い、都モニタリング会議におけるL452R変異株スクリーニング検査の報告が終了したことから、2021年11月11日（木曜日）をもって本グラフの数値更新を終了しました。'
```

すみません、東京都に確認したところ、一部テキストが間違っていたそうです。
こちらで修正してコミットしてしまいますね！ 🙇

2021-11-18 02:21 UTC, kaizumaki approved these changes

2021-11-18 04:05 UTC, merged